```{r solutions, echo=FALSE}
# This is optional to prevent annoying errors when deploying shiny apps
if(!exists(".flexteach_solutions"))
        .flexteach_solutions = FALSE
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
        echo = FALSE
        , dev = "svg"
        , dpi = 150
        , fig.width = 5
        , fig.height = 5
        , dev.args = list(pointsize=13)
        , out.width = "40%"
)
library(reticulate)
library(shiny)
```

## Exercise Example

Welcome! You can click the "show solutions" button at any time to see underlying code chunks.

1. Download the data above and import it into SPSS.

```{python echo = .flexteach_solutions}
# Import necessary python module
import pandas as pd
import scipy.stats as st
import numpy as np

# get the df generated by R
# https://stackoverflow.com/questions/49423429/how-to-access-an-object-attribute-with-a-dot-in-its-name/49424361
df = getattr(r,'.flexteach_info$data')

```

```{python echo = .flexteach_solutions}
# Split the dataframe into individual column
col_0 = df.iloc[:, 0]
col_1 = df.iloc[:, 1]

```

2. Calculate the mean of each column.

```{python echo = .flexteach_solutions}
# Here you calculate all the answer.
mean_0 = col_0.mean()
mean_1 = col_1.mean()

print("Mean of first column:", mean_0,"\n",
      "Mean of second column:", mean_1)
```

3. Calculate the 95% confidence interval of each column. Write your answer in the box below.

```{python echo = .flexteach_solutions}
ci_0 = st.t.interval(alpha=0.95, df=len(col_0)-1, loc=np.mean(col_0), scale=st.sem(col_0))
ci_1 = st.t.interval(alpha=0.95, df=len(col_1)-1, loc=np.mean(col_1), scale=st.sem(col_1))

print("95% CI of first column:", ci_0,"\n",
      "95% CI of second column:", ci_1)
```
```{r}
# Add Objective input field
add_input_field("q3_1","95% CI for column 0");
add_input_field("q3_2","95% CI for column 1");
```
4. Explain, in plain English, what does the 95% mean:

```{r}
# Add Subjective input field
tags$div(id="student_attempt_q4",class="rtfInput");
```

```{r automarking, echo = .flexteach_solutions}
# This chunk enables automarking.
tags$div(id="standard_ans_q2_1",class="standard_ans",py$mean_0,style="visibility: hidden");
tags$div(id="standard_ans_q2_2",class="standard_ans",py$mean_1,style="visibility: hidden");
tags$div(id="standard_ans_q3_1",class="standard_ans",py$ci_0,style="visibility: hidden");
tags$div(id="standard_ans_q3_2",class="standard_ans",py$ci_1,style="visibility: hidden");

```