---
title: "Check your assignments"
output: 
  flexdashboard::flex_dashboard:
    theme: yeti
    includes:
      in_header: !expr flexTeaching:::writeHeaders()
runtime: shiny_prerendered
---

```{r child="children/setup.Rmd"}
```

```{r child="children/query_string.Rmd"}
```

```{r, context="render"}
# Load a lib that provides copy-to-clipboard functionality
library(rclipboard)
shiny::includeScript(path = system.file("lib/clipboard.min.js", package = "rclipboard"))

```


Column {.sidebar}
-----------------------------------------------------------------------

```{r child="children/sidebar_main.Rmd"}
```

```{r child="children/sidebar_solve.Rmd"}
```

Column
------------------------------------

```{r context="server"}
#"entry" is either solve or download
entry <- function (){
  return("solve");
}

seed <- reactive({
  input$seed
})

solutions <- reactive({
  input$solutions
})

```

```{r child="children/content.Rmd"}
```

<script>
//Clicking the "show_admin" button (un)folds the admin panel
$(document).ready(function () {
  $("#admin_panel").hide();
  $("#show_admin").on("click", function() {
    $("#admin_panel").toggle();
  });
});
</script>


