```{r setup, include=FALSE, context="setup"}
options(shiny.fullstacktrace = TRUE)
library(broom)
library(gt)
library(tidyr)
library(flexdashboard)
library(magrittr)
library(dplyr)
library(flexTeaching)
library(QuantPsyc)

knitr::opts_chunk$set(echo = FALSE)

all_assignment_data =  flexTeaching:::getAssignments(simple = FALSE)

globals = new.env()
```
```{r context='setup'}

# https://stackoverflow.com/questions/23599268/include-a-javascript-file-in-shiny-app
# TODO move to setup.rmd
HTML('<head>
               <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.6.0/jszip.js"></script>
               <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.8/FileSaver.js"></script>
               <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
               <script src="https://cdnjs.cloudflare.com/ajax/libs/intro.js/4.1.0/intro.min.js" integrity="sha512-vpRYyG0wwpTzFdMa1fWEV6GLWfJiiKG1W7dCPuIuvm2kbZMUA8jnokV84rdUft8AF6ih83/ItbmP/fDzNjVxsA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
               <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intro.js/4.1.0/introjs.min.css" integrity="sha512-631ugrjzlQYCOP9P8BOLEMFspr5ooQwY3rgt8SMUa+QqtVMbY/tniEUOcABHDGjK50VExB4CNc61g5oopGqCEw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
          <script type="text/javascript" src="www/util.js"></script>
              <script type="text/javascript" src="www/responseStroage.js"></script>
          </head>')

```

```{r, echo=FALSE}
# Boilerplate code for importing shinyjs in rmd, the same below
shiny::addResourcePath("shinyjs", system.file("srcjs", package = "shinyjs"))
```
```{r, context="server"}
shinyjs::useShinyjs(html = TRUE)

```
<script src="shinyjs/inject.js"></script>

```{r cache, eval = params$cache_setup, context="server"}
shinyOptions(
  # Key-value cache stores with automatic pruning by age or max_size.
  cache = cachem::cache_disk(
    dir = "./my_app_cache",
    max_size = 512 * 1024^2,
    max_age = 60 * 60 * 24 * 10
    )
)
```

<!-- Include Quill stylesheet -->
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

<!-- Include the Quill library -->
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

<!-- Include the KaTex library For Formula Display in Quill -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.css" integrity="sha384-Um5gpz1odJg5Z4HAmzPtgZKdTBHZdw8S29IecapCSB31ligYPhHQZMIlWLYQGVoc" crossorigin="anonymous">

<!-- The loading of KaTeX is deferred to speed up page rendering -->
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.js" integrity="sha384-YNHdsYkH6gMx9y3mRkmcJ2mFUjTd0qNQQvY9VYZgQd7DcN7env35GzlmFaZ23JGp" crossorigin="anonymous"></script>

<!-- To automatically render math in text elements, include the auto-render extension: -->
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/contrib/auto-render.min.js" integrity="sha384-vZTG03m+2yp6N6BNi5iM4rW4oIwk5DfcNdFfxkk9ZWpDriOkXX8voJBFrAO7MpVl" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script>

<!-- react-quill https://github.com/zenoamaro/react-quill-->
<script src="https://unpkg.com/react@latest/umd/react.development.js"></script>
<script src="https://unpkg.com/react-dom@latest/umd/react-dom.development.js"></script>
<script src="https://unpkg.com/prop-types/prop-types.js"></script>
<script src="https://unpkg.com/react-quill@latest/dist/react-quill.js"></script>
<!--see https://reactjs.org/docs/add-react-to-a-website.html-->
<script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
<script type="text/babel" src="www/quill.js"></script>



