```{r context="render"}
uiOutput("assignmentbox")
uiOutput("idbox")
uiOutput("formatbox")
```

```{r context="server"}

session$allowReconnect(TRUE)

output$idbox <- renderUI({
  # If the query string has id specified, fill it into the input box
  query = getQueryString()
  seed = if ('id' %in% names(query)) query[['id']] else ""

  el = textInput("id", label = "ID:", width = "150px", value = seed, placeholder = "Your ID")

  #The query string can disable the id inputfield
  if('id_disable' %in% names(query)){
    return(shinyjs::disabled(el))
  }else{
    return(el)
  }
})

output$assignmentbox <- renderUI({
  query = getQueryString()
  assignment = query[['assignment']]
  cat_regex   = query[['category']]
  if(is.null(cat_regex))
    cat_regex = ""
  flexTeaching:::getAssignments() %>%
    mutate(
      hidden = case_when(
        !grepl(pattern = cat_regex, x = category) ~ TRUE,
        TRUE ~ hidden
      ) # Hide ones that don't match category regexp
    ) %>%
    {
      if(is.null(assignment)){
        filter(., !hidden)
      }else{ # But if the querysting has specify the hidden assignment, then it can be shown
        filter(., !hidden | (shortname == !!assignment))
      } # Filter out the hidden ones, except if we've specified it in the query string
    } %>%
    split(.$category) %>% # split by category
    purrr::map(function(el){ # extract the shortname as the displayed label
      z = pull(el, shortname)
      names(z) = pull(el, title)
      return(z)
    }) -> assignments

  el = selectInput("assignment", label = "Assignment:", width = "150px", choices = assignments, selected = assignment)
  if('assignment_disable' %in% names(query)){
    return(shinyjs::disabled(el))
  }else{
    return(el)
  }
})

output$formatbox <- renderUI({
  query = getQueryString()
  format = if ('format' %in% names(query)) query[['format']] else NULL
  el = selectInput("format", label = "Data format:", choices = names(flexTeaching:::formats), selected = format)
  if('format_disable' %in% names(query)){
    return(shinyjs::disabled(el))
  }else{
    return(el)
  }
})


```
