```{r context="render"}
tags$hr()
fileInput(inputId = "responses",
          label = "Upload responses",
          multiple = TRUE,
          accept = c(".html",".htm"))

actionButton("responses_download_button","Download Feedback")
#TODO an forward and backward button, replaced by a scroll list in the future.
actionButton("previous_responses_button","<-")
actionButton("next_responses_button","->")
```
```{r context="server"}
    observeEvent(input$responses_download_button, {
      #if (exists("varA")) {shinyjs::alert(varA);}
      session$sendCustomMessage(type = 'marking_download_onClick',
                                message = 'Currently no need for passing message')

  })

observeEvent(input$previous_responses_button, {
  #if (exists("varA")) {shinyjs::alert(varA);}
  session$sendCustomMessage(type = 'previous_response_onclick',
                            message = '')

})

observeEvent(input$next_responses_button, {
  #if (exists("varA")) {shinyjs::alert(varA);}
  session$sendCustomMessage(type = 'next_response_onclick',
                            message = '')

})

```

